name: lint-wf
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout / clone repository
        uses: actions/checkout@v4
      - name: install HTMLHint
        runs: npm install --save-dev htmlhint
      - name: lint HTML files
        run: npx htmlhint "**/*.html"
      - name: install Stylelint
        run: npm install --save-dev stylelint
      #- name: Lint CSS files
       # run : npx stylelint "**/*.css"
      - name: Display Package.json Contents
        run: cat package.json
       


